language: ruby

rvm:
  - 2.2.2
  - 2.2.3
  - 2.3.0
  - 2.3.1
  - 2.4.0
  - 2.4.1

gemfile:
  - gemfiles/rails_3.0.gemfile
  - gemfiles/rails_3.1.gemfile
  - gemfiles/rails_3.2.gemfile
  - gemfiles/rails_4.0.gemfile
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile

matrix:
  exclude:
    - rvm: 1.9.3
      gemfile: gemfiles/rails_4.0.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/rails_4.1.gemfile
    - rvm: jruby-19mode
      gemfile: gemfiles/rails_3.2.gemfile
    - rvm: jruby-19mode
      gemfile: gemfiles/rails_4.0.gemfile
    - rvm: jruby-19mode
      gemfile: gemfiles/rails_4.1.gemfile
    - rvm: rbx-2.2.1
      gemfile: gemfiles/rails_3.2.gemfile
    - rvm: rbx-2.2.1
      gemfile: gemfiles/rails_4.0.gemfile
    - rvm: rbx-2.2.1
      gemfile: gemfiles/rails_4.1.gemfile

before_script:
  - bundle
